### PR TITLE
[Hashlink] Added the additional parameters for Assets

### PR DESCRIPTION
**Pull request by Jarrio**
I also added the `pos` parameter for consistency ~ did not check if it was required.

### CODE REVIEW

**Comment by sh-dave** [comment]
I was a minute faster with #800 👅

**Comment by Jarrio** [comment]
But I added the `pos` position :D

**Comment by sh-dave** [comment]
But it'snot that useful here imo. The point in having it in `kha.Assets.loadXXX()` was to show the file/line where it's called from, and it's only used in the default version that just uses `haxe.Log.trace`.

**Comment by RobDangerous** [comment]
Sorry, Dave won the race.

**Pull request closed without merging**
