### PR TITLE
Reduce fileLoad functions

### PR DESCRIPTION
**Pull request by RblSb**
Before:
```haxe
imageLoad: function(done,failure) {
	var tmp;
	if(failure != null) {
		tmp = failure;
	} else {
		var f = haxe_Log.trace;
		var infos = { fileName : "kha/internal/AssetsBuilder.hx", lineNumber : 132,
			className : "kha._Assets.ImageList", methodName : "imageLoad"};
		tmp = function(v) {
			f(v,infos);
		};
	}
	kha_Assets.loadImage("image",function(image) {
		done();
	},tmp,{ fileName : "kha/internal/AssetsBuilder.hx", lineNumber : 132,
		className : "kha._Assets.ImageList", methodName : "imageLoad"});
}
```
After:
```haxe
imageLoad: function(done,failure) {
	kha_Assets.loadImage("image",function(image) {
		done();
	},failure,{ fileName : "kha/internal/AssetsBuilder.hx", lineNumber : 132,
		className : "kha._Assets.ImageList", methodName : "imageLoad"});
}
```

### CODE REVIEW

**Comment by sh-dave** [comment]
Looks like the default `trace` won't be called anymore in case you don't provide a custom reporter function?

**Comment by RblSb** [comment]
Error with pos info should be triggered inside of loadImage/loadEtc ([there is reporter call](https://github.com/Kode/Kha/blob/master/Sources/kha/Assets.hx#L233)).
I checked CORS error (from file://) and get errors like this in both cases:
`kha/Assets.hx:174: {url : sounds/fx_powerup_use_repair.mp3}`
So i think it should work for other cases too.

**Comment by RblSb** [comment]
How to trigger `AssetsBuilder.hx` error? Maybe that `posInfo` not required? Still think this is good change for dce and code size with many assets.

**Comment by sh-dave** [comment]
Oh, i actually only use the `loadXXXFromPath` functions so i don't have anything like that generated. But yeah i guess in your case it would save quite some size for these functions. To trigger an error it should be possible to stop after `System.start` and just delete a file out of the `build/target` folder.

**Comment by RblSb** [comment]
Tested `loadImageFromPath`, `loadEverything` and `imageLoad`, they all gives error to `Assets.hx` with `url: image.png` link. I only get `AssetsBuilder.hx` error with `Assets.images.imageLoad(()->{}, null)`. Should `error` arg be optional?

**Comment by RblSb** [comment]
Should be fine now.

**Comment by RblSb** [comment]
Maybe we can simply remove these macro functions and add `Assets.load(r:Resource)/unload` or `resource.load()/unload()`?

**Pull request merged**
