### PR TITLE
Simplify loadEverything

### PR DESCRIPTION
**Pull request by RblSb**
`loadEverything` only uses `Description` files (calls local `loadFunc` for file types instead of macro generated `Load` functions), so dce (or define) can remove other fields from AssetsLists in next pr step. Not sure if this helps, better to read new version instead of diff...

### CODE REVIEW

**Comment by RobDangerous** [comment]
So this is now on part of the Loader DCE pull request which means I'm supposed to merge this and close the other one, right?

**Comment by RblSb** [comment]
Right

**Comment by RobDangerous** [comment]
Nooo, now I did it the other way round.

**Comment by RobDangerous** [comment]
The force push is with me.

**Pull request merged**
