### PR TITLE
gamepad connect/disconnect events for html5

### PR DESCRIPTION
**Pull request by juakob**
#735 gamepad connect/disconnect events for html5

### CODE REVIEW

**Comment by RobDangerous** [comment]
Changes to Gamepad.hx are missing.

**Comment by juakob** [comment]
https://github.com/Kode/Kha/pull/735

**Comment by RobDangerous** [comment]
Aaah, three pull-requests for maximum confusion.

**Comment by juakob** [comment]
I like to keep things intresting hahaha

Sorry for that I'm on the country side and the internet dosent work too well, plus I have yo learn how to use Github the right way

**Comment by RobDangerous** [comment]
Normally you create a branch and then create a pull-request based on that. Then you can push more things into that branch and it's automatically added to the pull-request.

**Comment by juakob** [comment]
I see, clearly a better option. Will try that next time

**Pull request merged**
