### PR TITLE
Fix js_classic blob loading

### PR DESCRIPTION
**Pull request by RblSb**
I don't know bug reason, this flag only removes global closure.

### CODE REVIEW

**Comment by RobDangerous** [comment]
W00t, I don't understand a thing.

**Comment by RblSb** [comment]
If you compile debug-html5 target with `js_classic`, `loadEverything` and at least one blob in your assets - there is stuck on this line https://github.com/Kode/Kha/blob/master/Backends/HTML5/kha/LoaderImpl.hx#L189 (callback is never called, electron 4.0.1).

**Comment by RblSb** [comment]
This thing fixed in electron 6. I recommend to close this PR after vscode-electron-debug update.

**Comment by RobDangerous** [comment]
So the right thing to do is to ignore this pull request and just update Electron instead, right?

**Comment by RblSb** [comment]
Yes, there is khamake electron fix for newest versions.

**Comment by RblSb** [comment]
Fixed

**Comment by RobDangerous** [comment]
Haha

**Pull request closed without merging**
