### PR TITLE
KravurImage minor fix

### PR DESCRIPTION
**Pull request by RblSb**
Use `Image.fromBytes` if it's implemented.

### CODE REVIEW

**Comment by RobDangerous** [comment]
What does it fix?

**Comment by RblSb** [comment]
`Image.fromBytes` is faster on some targets

**Comment by RobDangerous** [comment]
Did you profile that? Looking at the Kore implementation, fromBytes actually looks worse. Think I'll have to have a closer look at those functions.

**Comment by RblSb** [comment]
Well, only with `haxe.Timer.measure` x)

**Comment by RobDangerous** [comment]
And what targets? And what are the results?

**Comment by RblSb** [comment]
Kore android and webgl, seems always faster. Webgl:
Current: 0.01
fromBytes: 0.0009
Kore:
Current: 0.15
fromBytes: 0.01
With any order.

**Comment by RobDangerous** [comment]
That's a lot. But we should have a look at that readable parameter in Kore's fromBytes, that makes it worse in other ways. And let's add fromBytes everywhere so we can get rid of the double whopper implementation before merging this.

**Comment by RblSb** [comment]
`fromBytes` is not implemented only on flash/android-java, will check it later. So, we should add `readable:Bool = false` as `fromBytes` last argument?

**Comment by RobDangerous** [comment]
Yes, I think we should do that.

**Comment by RblSb** [comment]
Achtung: this patch can cause crashes for some androids in `Kore::Graphics4::Texture::init(char const*, bool)`. Can't get more details sadly. Ideas?

**Comment by RblSb** [comment]
Lets revert KravurImage change and merge only api change?

**Pull request closed without merging**
