### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by RblSb**

### CODE REVIEW

**Comment by RobDangerous** [comment]
I'm very sorry but pull requests like this are very bad for me. It takes me less time to do a cleanup myself than to look through this. If you see specific cleanup needs, feel free to open some issues instead.

**Comment by RblSb** [comment]
Is first and third commits are ok as separate PRs?

**Comment by RobDangerous** [comment]
No. But a pull request for the feature you snuck in there would be ok (having an actual feature in a pull request called cleanup is really mean though).

**Comment by RblSb** [comment]
Sorry

**Comment by RobDangerous** [comment]
No worries 👍

**Pull request closed without merging**
