### PR TITLE
Image.fromFileBytes

### PR DESCRIPTION
**Pull request by romamik**
Function to create Image from file loaded from some external source. Implementation for Html5, Flash and Kore.

### CODE REVIEW

**Comment by romamik** [comment]
Checks fail because need Kore version that exists only in my fork.

**Comment by sh-dave** [comment]
Why is it called fromFileBytes; shouldn't matter if it's loaded from some file or a buffer created in memory imo? The ```fileExtension``` parameter seems strange as well. You basically just pass it around. Can't you just bind that to the error callback you're registering?

**Comment by romamik** [comment]
>Why is it called fromFileBytes; shouldn't matter if it's loaded from some file or a buffer created in memory imo? 
Yes, that's not perfect name. I just failed to think of better. There is already function with name fromBytes() which accepts raw image data, already decoded from image file format. So to distinguish from this function I used this name. 
If somebody have better name for this function - I'm ready and will be glad to rename.

>The fileExtension parameter seems strange as well. You basically just pass it around. 
On flash and Html5 it is not used, but it's used in Kore: it uses file extension to determine the file format.
I think it's possible to make Kore determine file format based on contents of the file rather then the file extension, but this will require hard testing. You can never know where it will break after such changes...

>Can't you just bind that to the error callback you're registering?
Sorry, but I did not understand what you mean.

**Comment by sh-dave** [comment]
If ```fromBytes()``` is already decoded, then ```fromUndecodedBytes()``` or ```fromRawBytes()``` maybe?

And forget what i said about the parameter, i missed the format check in Kore and thought it's only used for the error callback.

**Comment by romamik** [comment]
In my opinion raw bytes are accepted by fromBytes, not by my function. Also it's not correct to say that fromBytes accepts uncompressed bytes, because they not nececary were ever compressed. 

May be we can rename fromBytes to fromRawBytes, but this is a breaking change, so no, this is not good. May be we can call my fuction fromCompressedBytes, even if they are not necesary compressed.

**Comment by romamik** [comment]
I rebased this pull request...

**Comment by romamik** [comment]
I've decided to have this code external to kha: https://gist.github.com/romamik/cefe4ad27ffd0da3b7b02985b12233fb
Closing this pull request.

**Comment by RobDangerous** [comment]
I might still resurrect this if it's ok for you, still have to have a closer look.

**Comment by romamik** [comment]
Yes, I can reopen this if you think so.
The main reason why I reimplemented this as external code is that it's easier for me to maintain my project up to date with latest kha in this way.

Also I feel that Kore implementation is a bit hacky. Right way is to make Kore::Image constructor accept Reader instead of filename, but this involves changing Texture because it is inherited from Image, and which is platform dependent, so the changes will be in every target. And I do not have possibility to test every target.

**Comment by RafaelOliveira** [comment]
This is very useful, because can be used to resolve https://github.com/Kode/Kha/issues/219 (load a image from web), together with haxe.Http. I tested it now in Windows, and it worked. For me this is very important.

**Comment by sh-dave** [comment]
I also think this would be a very welcome addition.

**Comment by RobDangerous** [comment]
Added a non-hacky Kore implementation. Please test because I didn't.

**Comment by romamik** [comment]
>Please test because I didn't.
:))) you are real jedi!!!

31 янв 2017 г. 5:55 PM пользователь "Robert Konrad" <
notifications@github.com> написал:

Added a non-hacky Kore implementation. Please test because I didn't.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/Kode/Kha/pull/440#issuecomment-276384692>, or mute the
thread

**Comment by RafaelOliveira** [comment]
It works for Windows, but not for html5. I'm testing with haxe.Http, and converting the data with Bytes.ofString() (Http receives the bytes as string). The bytes are being received, but Image.fromEncodedBytes doesnt work and call the errorCallback.

To test with Http this need to be tested in KodeStudio because Electron doesnt have crossorigin restrictions.

**Comment by RobDangerous** [comment]
No idea whether haxe.Http is the right thing to use for binary files.

**Comment by romamik** [comment]
Yes, haxe Http class is not suited for binary files. It by chance works for sys (c++ and neko) target, but for js and flash it just do not work. I have the class that handles this, I can't make it open source, but basic idea is very simple:
```haxe
    class BinaryHttp {
        getBytes(url:String):Promise<Bytes> {
           var deferred:Deferred<Bytes> = new Deferred();
           #if js 
		request = Browser.createXMLHttpRequest();
		request.onload = fucnction() deferred.resolve(Bytes.ofData(cast(request.response, BytesData)));
		function onError() throw 'Error';
		request.onerror = onError;
		request.onabort = onError;
		request.responseType = ARRAYBUFFER;
		request.open('get', url, true);
		request.send();
           #elseif flash
                //var loader = new URLLoader();
                //loader.dataFormat = URLLoaderDataFormat.BINARY;
                #error
           #elseif sys
                var http = new Http(httpBytes.url);
                http.onError = function(_) throw 'error';
                http.onData = function(data:String) deferred.resolve(Bytes.ofString(data));
                http.request();
           #else
               #error
           #end
           return deferred.promise();
        }
    }
```
This code was not tested, but gives the idea.

**Comment by romamik** [comment]
Also, I must say, that if you really need to download file from web and show, then downloading it like that and showing using code from this pullrequest makes some overhead: image is downloaded as byte array, encoded to base64, then decoded from base64, then decoded from image file format, and only then uploaded to videomemory. While it's completely possible to avoid encoding/decoding from base64: you need to create  element with src=url of picture and then create kha image from element (look at the code from pullrequest, it does exactly this, just with data url).

**Comment by RafaelOliveira** [comment]
For html5 Assets.loadImageFromPath() already works, and it creates a image element, so the use of Http in html5 was just for testing.

**Comment by RobDangerous** [comment]
loadBlobFromPath might work for you then.

**Pull request merged**
