### PR TITLE
Add missing fmt lib file

### PR DESCRIPTION
**Pull request by Onek8**
Ran into a couple issues without it for the armory networking such as /usr/bin/ld: kore_sources.o: in function `haxe_crypto_Sha1_make':
kore_sources.c:(.text+0x49ea4): undefined reference to `fmt_digest'

### CODE REVIEW

**Comment by Onek8** [comment]
Thank you for your work in making everything khampatible! Hopefully I can be more helpful soon I am still learning. I am currently receiving the same error without the fmt_crypto.c file however it is only one now with your changes to the fmt.c file
As a side note the hl kfile is still referencing the crypto file on line 6
project.addFiles('hl/include/mbedtls/library/**', 'hl/include/zlib/**', 'hl/libs/fmt/fmt_crypto.c', 'hl/libs/fmt/sha1.c', 'hl/libs/ssl/ssl.c');

**Comment by RobDangerous** [comment]
Not true: https://github.com/Kode/Kha/blob/main/Backends/Kinc-HL/kfile.js#L6

**Comment by Onek8** [comment]
How embarrassing :D I didnt reload the page

**Comment by RobDangerous** [comment]
So what error is left now?

**Comment by Onek8** [comment]
..... -static-libgcc -static-libstdc++ -pthread -lasound -ldl -ludev -lGL -lEGL

/usr/bin/ld: kore_sources.o: in function `haxe_crypto_Sha1_make':
../haxe/crypto/Sha1.c:20: undefined reference to `fmt_digest'
/usr/bin/ld: kore_sources.o:(.data.rel+0x2a80): undefined reference to `fmt_digest'
collect2: error: ld returned 1 exit status

**Comment by RobDangerous** [comment]
Can't repro that. Replaced https://github.com/Kha-Samples/Shader/blob/main/Sources/Main.hx#L47 with "i[2] = haxe.crypto.Sha1.make(haxe.io.Bytes.alloc(4)).get(0);" to test it and that compiles fine.

**Comment by Onek8** [comment]
Can confirm all is working well! It was mixup between my own project folders, thank you for your patience.

**Pull request merged**
