### PR TITLE
Report HTML5 file drop events

### PR DESCRIPTION
**Pull request by tong**
Not sure why this is hidden behind the `kha_debug_html5`.

### CODE REVIEW

**Comment by tong** [comment]
Well, there seems to be no way to  actually read the contents of the dropped file, maybe that's why.
Also wondering how this could fit into current api.

**Comment by zshoals** [comment]
> 
> 
> git blame to the rescue - hey @zshoals, what do you think of this?

git blame lies. This was the first PR I made to Kha and you can see that that conditional compilation block is still in there: https://github.com/Kode/Kha/pull/1227

**Comment by RobDangerous** [comment]
Ah, indeed. It was @sh-dave! Hey Dave, can we remove that #if?

**Comment by sh-dave** [comment]
I think i never tested this in a browser, so sure, go ahead and remove the ifdef if it's working properly.

**Comment by RobDangerous** [comment]
Let's go and hope for the best.

**Pull request merged**
