### PR TITLE
update blob loading code for electron 4+

### PR DESCRIPTION
**Pull request by sh-dave**
@Joncom can you check if this also fixes your font loading problems?

### CODE REVIEW

**Comment by RobDangerous** [comment]
Have to test with Kode Studio's electron...

**Comment by Joncom** [comment]
@sh-dave, what font loading problem are you referring to?

**Comment by sh-dave** [comment]
Oh sry, i think it was Antriel in IRC, not you :angel:

**Comment by Antriel** [comment]
Can confirm this fixed my issue of `Assets.loadEverything` never finishing loading a font file (images worked fine), with VSCode using extensions Kha@19.2.0, Kha Extension Pack@18.9.0.
Kode Studio@18.11.0 works fine.

**Comment by RobDangerous** [comment]
Also works fine in Kode Studio.

**Pull request merged**
