### PR TITLE
add parentheses  to avoid optimization error

### PR DESCRIPTION
**Pull request by juakob**
when use with analyzer-optimize the line gets optimize wrong, even in haxe 4.1

### CODE REVIEW

**Comment by sh-dave** [comment]
Like i wrote in the IRC, i don't see the need for Syntax.code() here.

```haxe
public static function getTime(): Float {
	final now = js.Browser.window.performance != null ? js.Browser.window.performance.now() : js.lib.Date.now();
	return now / 1000;
}
```

**Comment by RobDangerous** [comment]
And didn't you say that it works in Haxe 4.1 yesterday?

**Comment by juakob** [comment]
So sorry Dave, I miss your comment in the log, thats a better solution.
Sorry Rob, I fail you, I thought it was working but later I found that notepad++ was showing the old file build using parentheses

**Comment by RobDangerous** [comment]
ok, then let's use Dave's version.

**Pull request closed without merging**
