### PR TITLE
Keyboard.disableSystemInterventions

### LINKED ISSUE #1064: Keyboard.disableSystemInterventions
Enum with `Full / None / Custom(keys:Array<KeyCode>)` constructors to change default key behavior in html5.

### PR DESCRIPTION
**Pull request by RblSb**
I added `Default` for current option (allow F-keys and chars, blocks ctrl/cmd hotkeys and backspace).
Also i think `Custom(func: (code: KeyCode)->Bool)` would be more useful than `Array<KeyCode>`.
Thoughts?
Closes #1064

### CODE REVIEW

**Comment by RblSb** [comment]
Found that firefox clipboard hack is not requred, `canvas.onpaste` works, the problem was in `onkeydown preventDefault` for x/c/v.
Good time to start adding browser-specific keycodes and unify them. How about this:
```haxe
case 186: Semicolon;
case 187: Equals;
case 189: HyphenMinus;
```
The problem that this is breaking change. Only firefox uses original `kha.input.KeyCode` values for these methods.
[from this](https://github.com/ccampbell/mousetrap/pull/215):
```
  ;   FF  59  Chrome 186  IE 186  Saf 186  
  =   FF  61  Chrome 187  IE 187  Saf 187 
  -   FF 173  Chrome 189  IE 189  Saf 189 
```
So then `if (key == 186)` in user code cannot be catched. We can change `Semicolon/etc` values and break `if (key == Equals)` instead.

**Comment by RblSb** [comment]
Robert, do you want to change these keycodes to chrome version?
Also would be interesting to find list of keycodes for native targets.

**Comment by RobDangerous** [comment]
The Kinc keycodes are here: https://github.com/Kode/Kinc/blob/master/Sources/kinc/input/keyboard.h
Ideally that should always be used.

**Comment by RblSb** [comment]
Okay, will change Kha's `KeyCode` class about these three keys to Kinc version and will do browser-specific checks to make it work.

**Comment by RobDangerous** [comment]
Super cool, thanks!

**Pull request merged**
