### PR TITLE
More math functions

### PR DESCRIPTION
**Pull request by malublu**
What you think about it?
Not finished yet only a idea!

### CODE REVIEW

**Comment by sh-dave** [comment]
```haxe
public inline function translate(tx:FastFloat = 0, ty:FastFloat = 0):FastMatrix3 {
...
}
```
Don't use default  arguments, thats slow code on native and doesn't make sense to have in the first place.

---

Matrices already have ```identity()``` iirc.

---

```haxe
class FastVector2 {
...
    public inline function clone():FastFloat {
        return new FastFloat(x, y);
    }
...
}

class FastVector3 {
...
    public static inline function clone():FastVector3 {
        return new FastVector3(x, y, z);
    }
    
    public static function toFast():kha.math.FastVector3 {
        return new kha.math.FastVector3(x, y, z);
    }
...
}
```
Did you even try to use some of these functions? Thats broken just by reading it...

---

```haxe
public inline function set(x:Int, y:Int, value:Float) {
   ...nested switch nonsense...
}
```
Just access _00, _10 ... whatever directly

---

I'm sure there is a lot more i missed...

**Comment by malublu** [comment]
Year I know.
That's because I said it's not finished yet. Only an idea.
But what's about the main idea with skew,rotate,translate functions?
The functions are only ported from my very old library (other language).

The set function are not really needed.
Sorry for that, but I only copy paste my code and modified the syntax, etc....
I would make a complete rework of the function.

Should the skew, rotate, etc.. function modify the matrix or should they create a new matrix?

It can be faster if you modify the matrix.
Like:

```
matrix.skew(...);
matrix.rotate(...);
```

Instance of:

```
// A matrix created, that you don't need (after skew)
matrix.skew(...).rotate(...);
```

**Comment by sh-dave** [comment]
Current matrices are immutable, so i would keep it that way. They're usually inline so they don't actually allocate a new object at runtime. To modify the ```this``` matrix you can just call ```setFrom()``` with the result of the computation.

**Comment by RobDangerous** [comment]
Sorry but let's keep it minimal in Kha itself.

**Pull request closed without merging**
