### PR TITLE
Unity Backend Update

### PR DESCRIPTION
**Pull request by williamthompsonj**
Updated shaders to use current array<blob>, array<string> convention instead of blob, string.

Normalized white space to use \n for all line endings, removed unnecessary whitespace.

Updated keyboard sendUpEvent and SendDownEvents to use KeyCode instead of Key.

Added empty functions for required functions defined by extern classes.

Updated several extern classes to follow haxe 4 standards.

Created the following files:
- audio\Audio.hx
- Display.hx
- netsync\Network.hx
- Window.hx

### CODE REVIEW

**Comment by RobDangerous** [comment]
Please revert the Non-Unity files, then I can merge it.

**Comment by williamthompsonj** [comment]
I reverted the changes to non-unity files but it won't compile without them

**Comment by RobDangerous** [comment]
Well, it shows zero changed files now, I don't know how that should break the build.

**Comment by williamthompsonj** [comment]
I did a full revert and tried to build locally, I'll commit with just the unity files so you can see

**Comment by williamthompsonj** [comment]
I was on holiday until yesterday, sorry for the long delay coming back to this

**Comment by williamthompsonj** [comment]
These are the errors it generates when I try to compile without the other file changes:

`%kha%\Sources/kha/audio2/ogg/vorbis/VorbisDecoder.hx:116: characters 9-15 : Array access is not allowed on kha.arrays.Float32Array
%kha%\Sources/kha/audio2/ogg/vorbis/VorbisDecoder.hx:138: characters 8-14 : Array access is not allowed on kha.arrays.Float32Array
%kha%\Sources/kha/audio2/ogg/vorbis/Reader.hx:113: characters 23-29 : Array access is not allowed on kha.arrays.Float32Array
%kha%\Sources/kha/audio2/ogg/vorbis/Reader.hx:113: characters 23-29 : For function argument 'x'
%kha%\Sources/kha/Sound.hx:75: characters 5-21 : Array access is not allowed on kha.arrays.Float32Array
%kha%\Sources/kha/Sound.hx:76: characters 5-21 : Array access is not allowed on kha.arrays.Float32Array
%kha%\Sources/kha/Sound.hx:83: characters 5-21 : Array access is not allowed on kha.arrays.Float32Array
%kha%\Sources/kha/graphics4/Graphics2.hx:174: characters 27-42 : Too many arguments
%kha%\Sources/kha/graphics4/Graphics2.hx:445: characters 31-54 : Too many arguments
%kha%\Sources/kha/graphics4/Graphics2.hx:430: characters 27-42 : Too many arguments
%kha%\Sources/kha/graphics4/Graphics2.hx:626: characters 27-42 : Too many arguments`

**Comment by RblSb** [comment]
Just add array access to Unity's `kha.arrays.Float32Array`, i guess:
https://haxe.org/manual/types-abstract-array-access.html

**Comment by williamthompsonj** [comment]
Yes, that does make more sense. I changed the non-unity files to use array.set() and array.get() syntax but adding normal array access makes more sense. Now the only error I get is this:

- %kha%/Sources/kha/graphics4/Graphics2.hx:174: characters 27-42 : Too many arguments
- %kha%/Sources/kha/graphics4/Graphics2.hx:445: characters 31-54 : Too many arguments
- %kha%/Sources/kha/graphics4/Graphics2.hx:430: characters 27-42 : Too many arguments
- %kha%/Sources/kha/graphics4/Graphics2.hx:626: characters 27-42 : Too many arguments

Specifically this refers to this code:
`rectVertexBuffer.unlock(bufferIndex * 4);`

**Comment by RobDangerous** [comment]
No need to argue about that, just add the arguments.

**Comment by williamthompsonj** [comment]
Hah, you have a good sense of humor, I wondered if you would make a joke like that. I have added the optional arguments to the function in the unity backend to support these calls. Now there are no errors when I compile.

**Comment by RobDangerous** [comment]
Excellent!

**Pull request merged**
