### PR TITLE
Fix KoreHL Image format

### PR DESCRIPTION
**Pull request by RudenkoArts**
To prevent this type of mistakes i set props setter from null to never 😬

### CODE REVIEW

**Comment by RobDangerous** [comment]
What is "this type of mistakes"?

**Comment by RudenkoArts** [comment]
I mean, i accidently set value to image.format, and its property with setter null. Instead of image.myFormat. [here](https://github.com/Kode/Kha/pull/1268/commits/e422dc2b3b84cf53676eb292cbb29cc263d21a61#diff-e2776c67871e33e51e744fe08b5d74c66eb19c1dc806644faee7c60cc3aaf74fL145)

**Comment by RudenkoArts** [comment]
In this [PR](https://github.com/Kode/Kha/pull/1263) i made mistake

**Comment by nadako** [comment]
Note that `get,null` will create a physical field on the class as well, which is completely unused in this case, so `get,never` is much better for getter-only properties.

**Comment by RobDangerous** [comment]
OK, I get it :)

**Pull request merged**
