### PR TITLE
Implement Storage for HL

### PR DESCRIPTION
**Pull request by RblSb**

### CODE REVIEW

**Comment by RobDangerous** [comment]
Hey, we talked about this - this pull request is not correct, the Kinc API can't be used that way and what you did only works because the Kinc-side non-console implementation is not yet correct. Sorry.

**Comment by RblSb** [comment]
Should i use Kore's FileReader instead?

**Comment by RobDangerous** [comment]
Yes. I'll change the Storage interface when I get to it though.

**Comment by RblSb** [comment]
Ok, will wait for async interface first.

**Comment by RobDangerous** [comment]
Okidoki. Sorry again, please send letters to Nintendo, Sony and Microsoft about how annoying this is.

**Comment by RblSb** [comment]
Thats fine, just played a little around c, hl and kinc, even fix fun problem. Hlc generates pretty clean code btw :p

**Comment by RobDangerous** [comment]
Yes and it compiles fast. But it runs slower than hxcpp and as long as that's the case I'll prioritize hxcpp.

**Pull request closed without merging**
