### PR TITLE
AssetData type

### PR DESCRIPTION
**Pull request by RblSb**
It's time to properly type our code! https://github.com/HaxeFoundation/haxe/issues/8484

### CODE REVIEW

**Comment by RblSb** [comment]
Meh, let's skip this i guess

**Comment by sh-dave** [comment]
why did you close this?

**Comment by RblSb** [comment]
Robert says this typedef is hard and restrict custom file types.

**Comment by RobDangerous** [comment]
"Robert says" is reason enough for anything and everything.

**Comment by sh-dave** [comment]
hm ok then

(but technically, it doesn't restrict anything as you can still Reflect.field() on the object, you just won't see it in code completion)

**Pull request closed without merging**
