### PR TITLE
Normalize White Space

### PR DESCRIPTION
**Pull request by williamthompsonj**
Main thing about this push
- Make all line endings cr+nl so unity stops throwing warnings about line endings

Remove white space in following places:
- On right side of line
- Between code and semi-colon
- Empty brackets, braces, and parens
- Beginning and end of file
- Turn 3+ new lines into 2

### CODE REVIEW

**Comment by RobDangerous** [comment]
Noooo, please use just \n.

**Comment by williamthompsonj** [comment]
Oh, I got it. Give me just a minute and I'll have that for you.

**Comment by RobDangerous** [comment]
Thanks!

**Comment by RblSb** [comment]
And now every PR diff is broken for some reason?  Also, removing newline at eof is awful idea for git.

**Comment by RobDangerous** [comment]
Oh no, did it remove the final new line?

**Comment by RblSb** [comment]
Yep

**Comment by RobDangerous** [comment]
Sorry william, I'll have to handle that myself. I used the force to reset the world to it's previous state.

**Comment by RblSb** [comment]
We can just add newlines maybe now instead of revert?

**Comment by RobDangerous** [comment]
Nah, better do this step by step, I didn't consider the consequences.

**Comment by williamthompsonj** [comment]
My apologies, I didn't realize wacking the new line at the end of file would cause a problem. I can force it to keep that new line without much effort.

**Comment by williamthompsonj** [comment]
Now that I think about this a second or two I'll just do a commit for the unity backend so it doesn't interfere with anyone else doing pull requests.

**Comment by RobDangerous** [comment]
Yes, please. I'll do a haxe-checkstyle pass at some appropriate time.

**Pull request merged**
