### PR TITLE
renamed Audio & Video capture to AudioCapture & VideoCapture

### PR DESCRIPTION
**Pull request by lewislepton**
just a simple renaming. keeping the folder layout.

### CODE REVIEW

**Comment by RobDangerous** [comment]
I think you also have to change something in the HTML5 backend to make that work.

**Comment by lewislepton** [comment]
ah ok. will do

**Comment by lewislepton** [comment]
forgot to recursive clone so just trying it again & get some tests done. should be done soon

**Comment by lewislepton** [comment]
ok. tested properly after recursive clone. all working

**Pull request merged**
